sudo: false
language: node_js
node_js:
  - "7"
before_install: 
  - npm install -g phantomjs grunt-cli bower
install: 
  - npm install 
  - bower install
  - grunt build

#before_script: grunt build

